### ISSUE TITLE
Run command; E2E

### ISSUE THREAD

**Issue by toien44** [rokucommunity/rooibos#1]
Sorry this is not an issue and can be delete after it's answered, but I'm looking into your repo and wondering if this can do end 2 end testing? Also I cloned your repo and want to perform the sample AssertionTests.brs, but do not see a run command. Thanks, new to brightscript and Roku testing.

**Comment by georgejecook** [comment]
hey - sorry I didn't get back to you.

It can test anything that executes brightscript code. We use it for integration and unit testing. I code using TDD (much of the time) - it works well with views, especially with MVVm Pattern or similar.

The docs have been updated by @bvisin, with instructions on how to build. There's extensive docs on how to run the tests, in both the documentation and makefiles for the main tests suite, and the sample app.

Hope that helps.
