### ISSUE TITLE
Rooibos_ReportCodeCoverage() not included in scope for rooibosDist.brs 

### ISSUE THREAD

**Issue by AliceB-aus** [rokucommunity/rooibos#103]
In rooibosDist.brs the function Rooibos_ReportCodeCoverage() is called but not instantiated anywhere within the code that I could find. 

Error from vs-code bright script extension. 
Cannot find function with name 'Rooibos_ReportCodeCoverage' when this file is included in scope 'source'

**Comment by georgejecook** [comment]
Thanks for raising your issue; sorry for not responding sooner. I'll try and get this resolved today :)

I'm thinking I'll add a brs ignore to this line.

**Comment by georgejecook** [comment]
resolved in rooibos 4.0.0
