### ISSUE TITLE
Properties out of sync for RBS_CMN_NodeContains()

### ISSUE THREAD

**Issue by AliceB-aus** [rokucommunity/rooibos#104]
The function is declared with two properties 
`function RBS_CMN_NodeContains(node , value) as boolean `

But within rooibosDist.brs it is used by parsing in three properties 
`if  RBS_CMN_NodeContains(node, value, key)`

**Comment by georgejecook** [comment]
Thanks for raising your issue; sorry for not responding sooner. I'll try and get this resolved today :)

**Comment by georgejecook** [comment]
resolved in rooibos 4.0.0
