### ISSUE TITLE
`EqArray` vs `EqArrays` Documentation mismatch

### ISSUE THREAD

**Issue by bvisin** [rokucommunity/rooibos#11]
https://github.com/georgejecook/rooibos/blob/6524f2ff5b12d58ae3b26d2fb283c4c05c0d1993/source/rooibos.cat.brs#L100

The documentation says `EqArray`
https://georgejecook.github.io/rooibos/module-BaseTestSuite.html#EqArray

but the function is actually `EqArrays`

**Comment by georgejecook** [comment]
fixed in dcbabc0
