### ISSUE TITLE
assertAAContainsSubset() does not fail if input array is not an AA

### ISSUE THREAD

**Issue by joseotavio** [rokucommunity/rooibos#111]
Not sure if this is the intended behaviour or not, but I noticed that the `assertAAContainsSubset()` function doesn't consider the assertion to have failed if the input `array` is not an AA. It even passes if I give it `invalid`, which I think is odd.

Given what the code does, it looks like it might have been a miss:

```
(...)
        else
            msg = "Input values are not an Associative Array."
            return m.getLegacyCompatibleReturnValue(false)
        end if
        m.currentResult.addResult("")
        return m.getLegacyCompatibleReturnValue(true)
```

I noticed the `msg` variable is assigned but not used, maybe the intention was to call `m.currentResult.addResult(msg)` at that point before returning?

**Comment by georgejecook** [comment]
fixed
