### ISSUE TITLE
Not able to run the test getting error VERSION MISMATCH

### ISSUE THREAD

**Issue by ckukadiya** [rokucommunity/rooibos#113]
![image](https://user-images.githubusercontent.com/43231930/88929521-dabdfc00-d297-11ea-8498-3b1da0d8f6bb.png)

**Comment by georgejecook** [comment]
Hi, 

this means that you do not have the right version of rooibos-cli installed
how are you preparing your tests? command line or with gulp/some other js tool chain?

**Comment by georgejecook** [comment]
closing this. please use latest rooibos 4.
