### ISSUE TITLE
Config is invalid in ConsoleTestReporter

### ISSUE THREAD

**Issue by turbidwater** [rokucommunity/rooibos#136]
I am trying to get Rooibos set up to run, but when I run the tests, I am getting an error because the config is invalid in ConsoleTestReporter.bs. For the line:
`if m.config.lineWidth <> invalid`
I get
`'Dot' Operator attempted with invalid BrightScript Component or interface reference.`

In my bsconfig-test.json I have specified the config for rooibos:
```
{
  "rootDir": "app",
  "files": ["**/*"],
  "stagingFolderPath": "dist",
  "retainStagingFolder": true,
  "autoImportComponentScript": true,
  "sourceMap": true,
  "plugins": ["@rokucommunity/bslint", "roku-log-bsc-plugin", "rooibos-roku"],
  "rokuLog": {
    "insertPkgPath": true
  },
  "diagnosticFilters": [
    {
      "src": "**/roku_modules/**/*"
    },
    {
      "src": "**/vendor/**/*"
    }
  ],
  "rooibos": {
    "isRecordingCodeCoverage": false,
    "printTestTimes": true,
    "testsFilePattern": "**/*.test.bs",
    "tags": ["!integration", "!deprecated", "!fixme"],
    "showOnlyFailures": true,
    "catchCrashes": true,
    "lineWidth": 70
  }
}
```
I've verified that it is using this file, because rooibos is not enabled in my bsconfig.json. Is there something I need to do to get this config into the test other than just put it in the bsconfig that's being used?

**Comment by turbidwater** [comment]
I've narrowed it down to in RooibosSession.js it can't find the runtime config here and so runtimeConfig is undefined:
```
addTestRunnerMetadata() {
    let runtimeConfig = this._builder.program.getFileByPkgPath(
      "source/rooibos/RuntimeConfig.bs"
    );
    if (runtimeConfig) {
      let classStatement = runtimeConfig.ast.statements[0].body.statements[0];
      this.updateRunTimeConfigFunction(classStatement);
      this.updateVersionTextFunction(classStatement);
      this.updateClassLookupFunction(classStatement);
      this.updateGetAllTestSuitesNames(classStatement);
      this.createIgnoredTestsInfoFunction(classStatement);
    }
  }
```
I tried changing the .bs to .brs, since that's the file extension of that file in the dist folder, but runtimeConfig is still undefined after that. So it never runs updateRunTimeConfigFunction

**Comment by georgejecook** [comment]
closing as this code is all irrelevant now.
