### ISSUE TITLE
Roku Developers Slack Link has expired

### ISSUE THREAD

**Issue by MikeAlMartinez** [rokucommunity/rooibos#154]
Would it be possible for you to create a new one? I'd be keen to join in with discussions there. 🙏

**Comment by TwitchBronBron** [comment]
Here's an updated link: https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA

Talk to you soon!

**Comment by MikeAlMartinez** [comment]
Thank you kind sir!
