### ISSUE TITLE
Premiere 3920x vs Express 4K+ 3941rw crash issue

### ISSUE THREAD

**Issue by c-wdolorito** [rokucommunity/rooibos#193]
Hello,

I'm running in to an issue working with this unit test framework.  I started out writing tests on an Express 4K+ 3941rw, then switched over to a Premiere 3920x.

![roku express 4k red 720](https://user-images.githubusercontent.com/115499129/194937250-ab9c1ae2-ce60-4139-bce4-6620a14367c5.png)
![roku permiere red 720](https://user-images.githubusercontent.com/115499129/194937271-f03f6ee7-dbe3-40d6-899a-5f3d629b80f9.png)

From above, what immediately stands out is firmware revision.  The Express 4K+ is on 11.0 while the Premiere is on 11.5.

The issue I'm running in to involves adding a global field to setup().  On the Premiere, it behaves as expected.  On the Express 4K+, there's a crash.  I've attached below a VSC project, cloned, pruned and added to from [https://github.com/georgejecook/rooibos-roku-sample](https://github.com/georgejecook/rooibos-roku-sample) as well the zip generated from that project.

Any help/ideas would be appreciated.  Even how to force my Express 4K+ to update to a newer firmware version, however my particular unit is a 3941rw, which isn't listed as a supported device according to [https://support.roku.com/article/228844467](https://support.roku.com/article/228844467).  It would at least rule out the possibility of it being a firmware issue if it were able to update.

Final notes, I'm developing on an M1 MacBookPro (18,1), macOS Monterey v12.6, using node v12.22.12, npm/npx v8.18.0.  I'm also using VSC v1.71.2 (Universal) with latest BrightScript Language extension (v2.35.2) as of this writing. 

[unit-test-issue-proj.zip](https://github.com/georgejecook/rooibos/files/9748425/unit-test-issue-proj.zip)
[unit-test-issue.zip](https://github.com/georgejecook/rooibos/files/9748428/unit-test-issue.zip)

**Comment by c-wdolorito** [comment]
Update on this issue on my end.  My Express 4K+ was able to update to firmware 11.5 this afternoon (11 Oct 2022) and the issue no longer exists.

**Comment by georgejecook** [comment]
Thanks for submitting. Sorry for lack of response. I will close this, due to the new firmware being released.
