### ISSUE TITLE
Support short-circuiting failed assertions in subs

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/rooibos#235]
When an expectation fails, rooibos will short-circuit the rest of the tests by running `return true`. This results in runtime crashes anytime the user writes `sub` instead. 

Please detect whether the function is a sub or a function and properly use `return` or `return true` accordingly. 

```brighterscript
sub test()
    m.assertTrue(false)
end sub
```

**Comment by georgejecook** [comment]
resolved in https://github.com/georgejecook/rooibos/pull/236
