### ISSUE TITLE
Add posibility to send results to a server

### ISSUE THREAD

**Issue by cazacutudor** [rokucommunity/rooibos#24]
We need to add possibility to send test results to a server.

**Comment by georgejecook** [comment]
I'll gladly accept a PR on this. I'm more focused on integrating rooibos with vscode these days.

**Comment by georgejecook** [comment]
this is a roadmap issue.

I say that we gather some requirements on this and see what we can do

**Comment by georgejecook** [comment]
Still up for doing this, especially with lcov compatible  code-coverage data in rooibos 3.0.0, which is going into beta in a moment..

If you've got any ideas on how this should look, now's a good time to pipe up

**Comment by georgejecook** [comment]
Update on this : A community member has contacted me to say they might be able to submit some socket code to the project. Waiting on further info about that.

**Comment by georgejecook** [comment]
I'm closing this, as I think it's better covered by #77
