### ISSUE TITLE
Update API docs for Stub

### ISSUE THREAD

**Issue by cazacutudor** [rokucommunity/rooibos#25]
The API documentation should be updated for Stub.

https://georgejecook.github.io/rooibos/module-BaseTestSuite.html#Stub
```
Stub(target, methodName, expectedArgsopt, returnValueopt, allowNonExistingMethodsopt) → {Object}
```

rooibos.cat.brs
```
function RBS_BTS_Stub(target, methodName, returnValue = invalid, allowNonExistingMethods = false) as object
```
The problem -> expectedArgs is not supported for Stub

**Comment by georgejecook** [comment]
addressed in #35
