### ISSUE TITLE
Stub methods are persisting across tests within the same suite

### ISSUE THREAD

**Issue by disc7** [rokucommunity/rooibos#282]
Issue is stubbed methods are persisting across tests within the same suite.
 
 This test is setting up the stubbed method (and is working when all tests within the suite are run):
 https://github.com/disc7/rooibosDemo/blob/main/tests/source/tests/Examples.spec.bs#L38

This test is working when run stand-alone (via @only annotation) and is failing when all tests with the suite are run:
https://github.com/disc7/rooibosDemo/blob/main/tests/source/tests/Examples.spec.bs#L49

Example is using the latest Rooibos version `5.12.0`.

**Comment by georgejecook** [comment]
The SUT object is a long lived singleton, so you are stubbing a function on it, then keeping a reference to the SUT object with a stubbed function

This isn't supported.


Mocks and stubs are destructive in rooibos - it's expected you'll create a new instance of an object to work with every time


Not closed to expanding the support to allow resetting of the original function; but that'd need to be a feature request and have someone go do it, as it's not a use case I promote

Should not be too hard to do though (just store the original function somewhere, and put it back on cleanup)
