### ISSUE TITLE
'@Only on an itgroup, can cause no tests to run if '@Only is on a different suite

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/rooibos#3]
This irksome little bug needs resolving.

if one suite has '@Only at the suite level, and another (different suite) has '@Only at the group level (but not suite) - then no tests will run.

**Comment by bvisin** [comment]
So what would the expected behavior be?  Detection and warning, or run the test and ignore the @only at the suite level?

**Comment by georgejecook** [comment]
I think always interpret any sub-testsuite `'@Only` as opting the suite itself into `@Only`. That's how it works for test cases.

the logic almost is - and should be - apply only at the most granular level where it's found.

Only on a test suite ... then ...  run all tests in suite suite, unless:
Only on a group ... then ...  run all groups marked with only
Only on a test .. then ...  run all tests marked with only

That makes sense in my mind - I just tried the fix now - it was simply marking the test suite as Only itself, if it has something more granular.

Works for testParams, Test It group and suites, as I expect.

https://github.com/georgejecook/rooibos/commit/6524f2ff5b12d58ae3b26d2fb283c4c05c0d1993
