### ISSUE TITLE
Update documentation and samples for `SGNode` testing 

### ISSUE THREAD

**Issue by episcopus** [rokucommunity/rooibos#30]
`SGNode` based testing needs to be updated to account for the inclusion of `rooibosFunctionMap.brs` in the `SGNode` subclass used as a test proxy. Not doing so results in issues accessing the generated function maps and such at test execution time.

Please update the following:
* https://github.com/georgejecook/rooibos/blob/master/docs/index.md#execute-tests-on-scenegraph-nodes
* https://github.com/georgejecook/rooibos/blob/master/samples/Overview/components/tests/NodeExampleTests.xml

As well as any other example that includes `SGNode` testing.

**Comment by georgejecook** [comment]
addressed in #35
