### ISSUE TITLE
testConfig.json Location

### ISSUE THREAD

**Issue by mcrowson** [rokucommunity/rooibos#43]
The docs and examples have the testConfig.json living in source/test/rooibos however the code has a default location of /source/test

[Example Location](https://github.com/georgejecook/rooibos/tree/master/samples/example/source/tests/rooibos)

[Default Location](https://github.com/georgejecook/rooibos/blob/master/dist/rooibosDist.brs#L1947)

**Comment by georgejecook** [comment]
Headsup - in 3.0.0-beta this is becoming part of the standard config. I've marked it as flagged for deprecation in the docs.

**Comment by georgejecook** [comment]
This file has been removed in 3.0.8 - see the rooibosC flags for a description of how to achieve the same effect
