### ISSUE TITLE
"showOnlyFailures": true not working

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#51]
Upon starting, testconfig is found and read by Rooibos, I get this log:
`Loading test config from default location : pkg:/source/tests/testconfig.json`

However, `"showOnlyFailures": true` doesn't affect the behavior, since I get all the successes as well.
I believe the configuration is being overloaded by Rooibos, since breaking a path such as `testPath` doesn't affect the behavior. This is my current config:

```
{
	"testPath": "pkg:/source/tests/specs",
	"logLevel": 1,
	"testsDirectory": "pkg:/source/tests/specs",
	"failFast": false,
	"showOnlyFailures": true,
	"maxLinesWithoutSuiteDirective": 30,
	"supportLegacyTests": false
}
```

**Comment by georgejecook** [comment]
this is resolved in 3.0.8 - 2 new flags -f showFailuresOnly and -F fail fast - the other settings are redundant
