### ISSUE TITLE
Add command to generate TestSuite for file/node from template

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#52]
An interesting feature which would make TDD more seamless would be to have a command such as `rooibosc --generate <TestSuiteName>` which would generate the corresponding `.xml` and `.brs` test suite files, with correct includes and dependencies. Maybe with parameters for the `SGNode` to extend or the file to include.

This could work with a template such as this:
components\tests\specs{{TestSuiteName}}Tests.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<component name="{{TestSuiteName}}Tests" extends="Node" xsi:noNamespaceSchemaLocation="https://devtools.web.roku.com/schema/RokuSceneGraph.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <interface>
        <function name="Rooibos_RunNodeTests" />
    </interface>
    <!-- Import test framework. -->
    <script type="text/brightscript" uri="pkg:/source/tests/specs/{{TestSuiteName}}Tests.brs" />
    <script type="text/brightscript" uri="pkg:/source/tests/rooibos/rooibosFunctionMap.brs" />
    <script type="text/brightscript" uri="pkg:/source/tests/rooibos/rooibosDist.brs" />
</component>
```
source\tests\specs{{TestSuiteName}}Test.brs:
```
'@SGNode {{TestSuiteName}}Tests
'@TestSuite
```

**Comment by georgejecook** [comment]
I like this idea; though I also have templates for vscode. Perhaps I should share and document those as well. Would you think that'd be better? seeing as vscode is where it's at for roku dev, these days.

**Comment by ronenlh** [comment]
I use the VSCode templates for Rooibos, they are great, but I don't think it's a good idea to make templates that are too big (such as the XML above). If you do make them they should be separate from the current snippets.
In the example above, they'd look somethin like this:
```
	"Rooibos xml": {
		"prefix": "aasub",
		"body": [
			"<?xml version=\"1.0\" encoding=\"utf-8\" ?>",
			"<component name=\"${1:SuiteName}Tests\" extends=\"Node\" xsi:noNamespaceSchemaLocation=\"https://devtools.web.roku.com/schema/RokuSceneGraph.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">",
			"    <interface>",
			"        <function name=\"Rooibos_RunNodeTests\" />",
			"    </interface>",
			"    <!-- Import test framework. -->",
			"    <script type=\"text/brightscript\" uri=\"pkg:/source/tests/specs/${1:SuiteName}Tests.brs\" />",
			"    <script type=\"text/brightscript\" uri=\"pkg:/source/tests/rooibos/rooibosFunctionMap.brs\" />",
			"    <script type=\"text/brightscript\" uri=\"pkg:/source/tests/rooibos/rooibosDist.brs\" />",
			"</component>",
		]
	},
```

**Comment by georgejecook** [comment]
oh - I'm not making myself clear - sorry - I use a template extension for vscode.
https://marketplace.visualstudio.com/items?itemName=brpaz.file-templates

I could make my templates available with the snippets - then you just right click - new file, enter in some names, and you're off to the races ;)

**Comment by ronenlh** [comment]
Ah, that would be great.
I don't know why I assumed snippets.
I didn't know about the extension.
