### ISSUE TITLE
BRIGHTSCRIPT: ERROR: roUrlTransfer.PostFromString: Sync-wait interrupted

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#55]
I get this error every time I run tests, as the last line, after coverage report:

```
BRIGHTSCRIPT: ERROR: roUrlTransfer.PostFromString: Sync-wait interrupted: pkg:/source/tests/rooibos/rooibosDist.brs(2205)
 ```

**Comment by georgejecook** [comment]
Is this still the case? I think I resolved this, and no longer have the message, running rooibosC 3.0.9 and rooibos 3.0.4

**Comment by ronenlh** [comment]
No, you fixed the bug. I'm closing the issue.
