### ISSUE TITLE
generate lcov/gcov file for front-end coverage report

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#58]
This will enable the use of extensions such as:
https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
https://marketplace.visualstudio.com/items?itemName=alexdima.vscode-lcov
https://marketplace.visualstudio.com/items?itemName=markis.code-coverage

there are node modules that can help with that:
https://www.npmjs.com/package/karma-sonarqube-unit-reporter

An lcov.info file looks like this:
```
TN:
SF:./components/ABC.brs
DA:5,0
DA:29,1
DA:33,1
end_of_record
TN:
SF:./components/File.brs
...
```

for it to work, the line num must be +1
and lines with zeros should be added as well.

**Comment by ronenlh** [comment]
Using the current data structures, I was able to cobble a script which prints a valid lcov file:
```
sub RBS_createLCov()
    ? "Generating lcov.info file..."

    cc = m.global._rbs_ccn
    expectedMap = cc.expectedMap
    filePathMap = cc.filePathMap
    resolvedMap = cc.resolvedMap

    buffer = ""

    for each module in filePathMap.items()
        moduleNumber = module.key
        filePath =     module.value
        packageName = "/XAAF"

        relativePath = filePath.replace("pkg:","."+packageName)
        sanitizedPath = relativePath.replace("\\", "/")

        buffer += "TN:" + chr(10)
        buffer += "SF:" + sanitizedPath + chr(10)

        for each expected in expectedMap[moduleNumber]
            lineNumber = expected[0]
            lineType =   expected[1]
            SHIFT = 1

            if resolvedMap[moduleNumber].doesExist(str(lineNumber)) then
                buffer += "DA:" + str(lineNumber+SHIFT) + ",1" + chr(10)
            else
                buffer += "DA:" + str(lineNumber+SHIFT) + ",0" + chr(10)
            end if
        end for

        buffer += "end_of_record" + chr(10)
    end for

    ?
    ? "+++++++++++++++++++++++++++++++++++++++++++"
    ? "LCOV.INFO FILE"
    ? "+++++++++++++++++++++++++++++++++++++++++++"
    ?
    ? buffer
end sub
```

Ideally the inner data structures should be different, generating an array of tuples of lines and times the line was called.

The file should be placed at the root of the project, and extensions such as ryanluker.vscode-coverage-gutters will highlight lines correspondingly.

**Comment by ronenlh** [comment]
Using the current data structures, I was able to cobble a script which prints a valid lcov file:
```
sub RBS_CreateLCov()
    ? "Generating lcov.info file..."

    cc = m.global._rbs_ccn
    expectedMap = cc.expectedMap
    filePathMap = cc.filePathMap
    resolvedMap = cc.resolvedMap

    buffer = ""

    for each module in filePathMap.items()
        moduleNumber = module.key
        filePath =     module.value
        packageName = "."

        relativePath = filePath.replace("pkg:", packageName)
        sanitizedPath = relativePath.replace("\\", "/")

        buffer += "TN:" + chr(10)
        buffer += "SF:" + sanitizedPath + chr(10)

        for each expected in expectedMap[moduleNumber]
            lineNumber = expected[0]
            SHIFT = 1

            if (resolvedMap[moduleNumber] <> invalid) and resolvedMap[moduleNumber].doesExist(str(lineNumber)) then
                buffer += "DA:" + str(lineNumber+SHIFT) + ",1" + chr(10)
            else
                buffer += "DA:" + str(lineNumber+SHIFT) + ",0" + chr(10)
            end if
        end for

        buffer += "end_of_record" + chr(10)
    end for

    ?
    ? "+++++++++++++++++++++++++++++++++++++++++++"
    ? "LCOV.INFO FILE"
    ? "+++++++++++++++++++++++++++++++++++++++++++"
    ?
    ? buffer
end sub
```
Ideally the inner data structure should be generated on the fly, with an array of tuples of lines and times the line was called, including zeroes. But if a different data design was intended then the script can do.

The lcov.info file should be placed at the root of the project, and extensions such as ryanluker.vscode-coverage-gutters will highlight lines correspondingly.

The sub as it is can be called at the end of `RBS_TR_Run()` somewhere after `RBS_ReportCodeCoverage()`.

I would also add a flag, to enable or disable it.

**Comment by georgejecook** [comment]
Hi, I've added, this, thanks for your submission!
