### ISSUE TITLE
design contribution

### ISSUE THREAD

**Issue by masudr4n4** [rokucommunity/rooibos#6]
Hallo dear 
I am a graphics designer.i am seeing that in your projects the logo is so simple.so i want to make a better logo for this projects.if you have any requirements then let me know.its totally free for open source projects.
Thank you.

**Comment by georgejecook** [comment]
I like my simple logo; but if you want to try something out, then feel free and attach it to this thread.

Very kind of you and good luck winning a ton of work. :)

**Comment by georgejecook** [comment]
Seeing as I've got no response, I'm closing this. If you want to offer your services again, then please email me at george [A T] tantawowa.com
