### ISSUE TITLE
Introduce Mutation Testing

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#63]
Mutation testing is interesting feature to introduce, and completely feasible with existent tooling. This would introduce coverage on the quality of existing tests themselves.

The program need to pre-process all existing code and capture possible mutations, such as:
- Logical operators: change range (> to >=), flip (> to <), negate (= to <>), etc.
- Mathematical operators: (change ++ to --), etc.
- Removing void-returning function calls (functions such as loggers, which don't change state, should be added to an ignore list).

After a list of mutations has be gathered per test suite, they are applied in a loop, running the tests suite after each change. If a test fails, the mutation is ''killed," if no tests fails, the mutation "survived."

Special care needs to be applied in BrightScript for the equality operator, not to be confused with the assignment operator, depending on the context.

Popular tools for other languages are [PIT](http://pitest.org/) and [Stryker](https://stryker-mutator.github.io/).

**Comment by georgejecook** [comment]
I have no problem with the concept; but I fail to see how this is `completely feasible with existent tooling`

I perceive the complete opposite.

As I understand it, this would require running multiple variations of the same code. This would be impossible for nodes; and for AA classes, would require a huge amount of runtime orchestration, which would perform extremely poorly.

Perhaps one could devise all of the various function permutations in a huge javascript map; but you must remember _there is no eval_ so every single permutation of every single function would have to exist before the app was deployed. That doesn't seem remotely feasible to me.

I'm leaving the issue open so you have a chance to respond with the mechanism by which you see this  working. I'm open to a discussion; but as it currently stands, I doubt this will ever get off the ground.

**Comment by ronenlh** [comment]
I was thinking with a deployment script which would deploy the app for every permutation.
However there would be no way to keep track across deployments, not that I know of.
Another option, in lieu of `eval`, would be to use the `run()` function, and dynamically load different versions of brs files.
Never tried the `run` function so maybe I'm wrong.

**Comment by georgejecook** [comment]
@ronenlh is this something you may implement? If not, I'd like to close it, as it's never going to be a priority for me.

**Comment by ronenlh** [comment]
I'm looking forward to work on this issue very soon (in the coming few months). It is a priority for me.
I'll might pick your brain as to what would be the best way to go forward with it, as most of the logic would be in the typescript preprocessor isn't it?

**Comment by ronenlh** [comment]
By the way, running time is not an issue, as mutation testing usually takes around 20 minutes to complete.

**Comment by ronenlh** [comment]
After some research, I'll be closing this issue. I'll be working part-time on a mutation testing tool that integrates with Rooibos, and for this I'll be opening more specific feature requests.

A few of them would be:

- more metadata on coverage testing, to be able to assign a piece of code with its corresponding test and while testing mutations, run only that test.
- machine-readable test results, so that automation tools can more easily be integrated to read the test output.
- the ability to disable integration tests, so as to reduce mutation test duration.
- the ability to output test results as a REST API request over the internet to a user-designated server.

I'm planning to write the tool as a typescript node application and seamlessly integrate with Rooibos. Hopefully to become part of the Roku developer's tool-chain for an industrial-standard CI/CD pipeline.

I'll be updating you on my progress. Thanks!

**Comment by georgejecook** [comment]
That sounds like a more sensible approach! good luck with it. Look forward to getting some integration prs down the line.
