### ISSUE TITLE
rooibosFunctionMap.brs exceeds Roku character count limit

### ISSUE THREAD

**Issue by twig2let** [rokucommunity/rooibos#65]
My client has a significant number (~3,000) of unit tests . When I attempt to pre-process all suites the resulting `rooibosFunctionMap.brs` does not load:

```
------ Compiling dev ------
*** ERROR compiling /pkg:/source/tests/rooibos/rooibosFunctionMap.brs:
Error loading file. (compile error &hb9) in pkg:/source/tests/rooibos/rooibosFunctionMap.brs
07-18 14:26:25.567 [scrpt.cmpl] Compiling App, id 'dev'
```

It appears this error is due to the generated file exceeding some Roku file, character count limit: **2,097,151**

I have created a [file](https://gist.github.com/twig2let/5eb5e607b069de240a0973000fb320c0) with **2,097,152** characters (one character over the limit) for you to replicate the issue.

I think we need some rule that will split the `rooibosFunctionMap.brs` up into smaller files when a particular test limit is exceeded.

**Comment by georgejecook** [comment]
I'm going to try and get this done over the next 2 weeks. Sorry I've been dragging my feet. Let me know if you need it sooner.

**Comment by georgejecook** [comment]
Closing this as I don't think it's an issue on rooibos 4.
