### ISSUE TITLE
support async testing

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/rooibos#69]
there are a few scenarios where async testing will be desirable. We have limitations in the language that will make this limited; at least until brighterscript supports async.

My suggestion is to be KISS and do the simplest thing that works.
My proposition is as follows

```
'@Test integration tests login
function someTest()
  'do test setup here
  'call some async thing
  '@Async 3000
  '@Await node.someField ' this is the node we will wait on
  '@Then
   'rest of the test
end function
```

What will then happen is, that the rooibos-cli will change this code as follows:
```
function someTest()
  'do test setup here
  'call some async thing
  m.RBS_observeField(node.someField, someTest_async_callback)
end function
function someTest_async_callback()
   'rest of the test
end function
```

This is a little verbose; but it allows us to replace the annotation lines with the observe call, end function, and function handler, without upsetting line numbers (which would require a source-map, which I simply don't have time to implement this year).

**Comment by twig2let** [comment]
Seems straightforward enough. I'm guessing there is a `Wait` in there somewhere too? 

Could the `@Async` and `@Await` be combined? E.g.

```
'@Test integration tests login
function someTest()
  'do test setup here
  'call some async thing
  '@Await 3000 node.someField ' this is the node we will wait on
  '@Then
   'rest of the test
end function
```

**Comment by georgejecook** [comment]
I've got an interim thing in the meantime, which works pretty well, I'll incoroprate it into the suite soon

**Comment by georgejecook** [comment]
I've added an interim solution for this, that owrks great in rooibos 3.6.1, so closing this now.
