### ISSUE TITLE
Emit error message when user forgets to add dependencies in test suite

### ISSUE THREAD

**Issue by ronenlh** [rokucommunity/rooibos#76]
I have spent too long to try to find the reason for a crash in the test suite.

`nodeStatResults` was invalid in `RBS_STATS_MergeTotalStatistic(totalStatObj, nodeStatResults)` and I couldn't find out why. (Rooibos_TestRunner.brs line 114)

This happened for two reasons:

- I forgot to add `Rooibos_RunNodeTests` interface in the test suite XML.
- I forgot to add Rooibos test framework import in the XML.

I believe there could be an invalid check for `nodeStatResults` and a corresponding error message for troubleshooting.

**Comment by georgejecook** [comment]
this is a great call out @ronenlh  - I think we should also make a test generator for rooibos-cli, to make this less likely, as well.

**Comment by georgejecook** [comment]
this was resolved in 3.6.1
