### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by michaelszutu** [rokucommunity/rooibos#89]
When I run my roku build all I see is:
Starting test using test scene with name TestsSceneTestsScene
#########################################################################
#TEST START : ###UNDEFINED_TEST_ID###
######################################################

# rooibos framework version: 3.2.2
# tests parsed with rooibosC version: 1.2.0
######################################################

[START TEST REPORT]

[END TEST REPORT]

Total  = 0 ; Passed  =  0 ; Failed   =  0 ; Ignored   =  0

 Time spent:  0ms

RESULT: Success

I do have a test.brs that resides in my source/tests/specs which, is included by NodeExampleTests.xml in components/test/specs
Not sure what's wrong here?

**Comment by georgejecook** [comment]
@michaelszutu sorry for not picking this up sooner; I don't know if you got the assistance you needed in the `#roobios` slack channel on the roku developers slack.

If not, please refer to the docs. I'm going to close this for now; feel free to reopen it and comment if you feel more action is necessary
